# Generated by Django 5.2.17 on 2026-09-09 05:45

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=160)),
                ('industry', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Professional services'), ('other', 'Other')], max_length=32)),
                ('company_size', models.CharField(choices=[('solo', 'Just me'), ('2-10', '2–10 people'), ('11-50', '11–50 people'), ('51+', '51+ people')], max_length=16)),
                ('country', models.CharField(default='PH', max_length=2)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_profile', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('legal_name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
