# Generated by Django 5.2.17 on 2026-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tax_identifier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_size',
            field=models.CharField(choices=[('solo', 'Just me'), ('2-10', '2 – 10 employees'), ('11-50', '11 – 50 employees'), ('51+', '51+ employees')], max_length=16),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso (PHP)'), ('USD', 'US Dollar (USD)'), ('SGD', 'Singapore Dollar (SGD)'), ('JPY', 'Japanese Yen (JPY)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='PHP', max_length=3),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='industry',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Trading / Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Professional services'), ('other', 'Other')], max_length=32),
        ),
    ]
