# Generated by Django 5.2.17 on 2026-09-09 06:21

import apps.tenancy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, upload_to='workspace-logos/%Y/%m/', validators=[apps.tenancy.validators.validate_workspace_logo]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Manila', max_length=64, validators=[apps.tenancy.validators.validate_timezone]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, validators=[apps.tenancy.validators.validate_workspace_slug]),
        ),
    ]
