# Generated by Django 5.2.17 on 2026-09-15 14:50

import apps.inventory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_description_product_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='product-images/%Y/%m/', validators=[apps.inventory.validators.validate_product_image]),
        ),
    ]
