# Generated by Django 5.2.17 on 2026-09-15 15:49

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_image'),
        ('tenancy', '0003_workspacesessiongrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('pcs', 'Pieces (pcs)'), ('box', 'Box'), ('pack', 'Pack'), ('set', 'Set'), ('kg', 'Kilogram (kg)'), ('liter', 'Liter'), ('meter', 'Meter')], default='pcs', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('key', models.SlugField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='inventory.productcustomfield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcustomfield',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='inventory_custom_field_tenant_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productcustomvalue',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'field'), name='inventory_custom_value_tenant_product_field_uniq'),
        ),
    ]
