# Generated by Django 5.2.17 on 2026-09-22 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_category_codes(apps, schema_editor):
    Category = apps.get_model("inventory", "Category")
    tenant_ids = Category.objects.order_by().values_list("tenant_id", flat=True).distinct()
    for tenant_id in tenant_ids:
        categories = Category.objects.filter(tenant_id=tenant_id).order_by("created_at", "pk")
        for number, category in enumerate(categories, start=1):
            category.code = f"CAT-{number:03d}"
            category.save(update_fields=("code",))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_created_by_alter_stockmovement_movement_type_and_more'),
        ('tenancy', '0003_workspacesessiongrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_category_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='inventory_category_tenant_code_uniq'),
        ),
    ]
