# Generated by Django 5.2.17 on 2026-09-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_references(apps, schema_editor):
    movement_model = apps.get_model("inventory", "StockMovement")
    prefixes = {
        "receipt": "GR",
        "issue": "SO",
        "adjustment": "ADJ",
        "transfer": "TR",
    }
    for movement in movement_model.all_objects.iterator():
        prefix = prefixes.get(movement.movement_type, "MV")
        movement.reference = (
            f"{prefix}-{movement.created_at.year}-{str(movement.pk)[:8].upper()}"
        )
        movement_model.all_objects.filter(pk=movement.pk).update(
            reference=movement.reference
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_code_category_created_by_and_more'),
        ('tenancy', '0003_workspacesessiongrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='counterparty_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_movements', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer_group',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(populate_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference', 'location'), name='inventory_movement_tenant_reference_uniq'),
        ),
    ]
